stages:
  - verify
  - deploy

include:
  - project: 'acquiring/devops/pipelines'
    ref: master
    file: '.appscreener.yml'

image: artifactory.raiffeisen.ru/ecom-image-docker/cli-tools:$CLI_TOOLS_TAG

variables:
  APP_NAME: ecom-cms-woo-commerce

push:
  stage: deploy
  script:
    - git config --global user.email $OPEN_SOURCE_GITHUB_EMAIL
    - git config --global user.name $OPEN_SOURCE_GITHUB_LOGIN
    - git push https://$OPEN_SOURCE_GITHUB_LOGIN:$OPEN_SOURCE_GITHUB_TOKEN@github.com/Raiffeisen-DGTL/$APP_NAME.git HEAD:main --force
  only:
    - master

